#!/bin/sh
CCTLDCENTRAL_DATABASE_NAME=cctldcentral \
CCTLDCENTRAL_DATABASE_USERNAME=cctldcentral \
CCTLDCENTRAL_DATABASE_PASSWORD=<password> \
CCTLDCENTRAL_DATABASE_HOST=<host>:5432 \
CCTLDCENTRAL_SCHEDULER_TIMEOUT=15s \
CCTLDCENTRAL_SCHEDULER_RETRIES=3 \
./cctldcentral
